config/routes.rb
Rails.application.routes.draw do
  resources :lunches, only: [:index]
  post 'lunches/upload', to: 'lunches#upload'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lunch.rb
class Lunch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index

  end

  def upload
    file = lunch_params[:file]
    @path = lunch_params[:path]
    @group_size = lunch_params[:group_size]

    if file.present?
      @path = Rails.root.join('tmp', file.original_filename)
      File.open(@path, 'w+b') do |f|
        f.write file.read
      end
    end

    # replace this company.yml with your own yaml file
    config_path = Rails.root.join('config', 'shuffle', 'company.yml')
    @groups = ShuffleService.call(file_path: @path, group_size: @group_size, config_path: config_path)
  end

  def lunch_params
    params.permit(:file, :group_size, :path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shuffle Lunch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper blue-grey darken-1">
      <a href="<%= lunches_path %>" class="brand-logo center">Shuffle Lunch</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
      </ul>
    </div>
  </nav>

  <%= yield %>
  </body>
</html>

app/views/lunches/_form.html.erb
<%= form_with(model: lunch, local: true) do |form| %>
  <% if lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% lunch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing Lunch</h1>

<%= render 'form', lunch: @lunch %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<div class="container" style="margin-top: 25px;">

  <% if notice %>
    <p id="notice" class="alert alert-warn">
      <%= notice %>
    </p>
  <% end %>

  <%= form_tag(lunches_upload_path, multipart: true, 'data-toggle': 'validator') do %>
    <div id="notice" class="alert alert-info">
      <div>
        <h5>Please make sure your CSV file contains the following columns before upload</h5>
        <ul>
          <li>・id</li>
          <li>・email</li>
          <li>・account</li>
          <li>・division_name</li>
        </ul>
      </div>
    </div>


    <div class="panel panel-default" style="margin-top: 10px;">
      <div class="panel-body">

        <div class="form-group">
          <div class="row">

            <div class="input-field col s2">
              <label class="col-sm-2">Set Group Size</label>
            </div>

            <div class="input-field col s2">
              <input id="group_size" placeholder="6" required="required" data-validate="true" data-required-error="*必須入力です" type="number" name="group_size" value="6"/>
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col s2">
            <label class="input-group-btn">
              <span class="btn btn-sm btn-primary">
                 Choose CSV File
                <i class="fa fa-upload"></i><input type="file" id="file-input" onchange="handleFiles(this.files)" name="file" accept="text/plain,text/tab-separated-values,text/csv" style="display:none" data-filesize="20" data-filetype="" required="required" data-required-error="Choose CSV File">
              </span>
            </label>
          </div>

          <div class="col s2">
            <%= submit_tag 'upload', id: 'upload-btn', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/lunches/new.html.erb
<h1>New Lunch</h1>

<%= render 'form', lunch: @lunch %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/upload.html.erb
<div class="container" style="margin-top: 10px;">
  <%= button_to 'shuffle', {:controller => 'lunches', action: 'upload', path: @path, group_size: @group_size}, {class: 'btn btn-primary'} %>

  <div style="margin-top: 10px; border: #666666">
    <table class="striped">
      <thead>
      <tr>
        <th>Group Name</th>
        <th>Group Members</th>
      </tr>
      </thead>

      <tbody>
      <% @groups.each do |k, v| %>
        <tr>
          <td><%= "Group_#{k+1}"  %></td>
          <td><%= v.join(" ") %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>